### ISSUE TITLE
README comment refers to deprecated option format

### ISSUE THREAD

**Issue by edmorley** [florianheinemann/express-sslify#10]
The comment in the example code snippet in the readme says:
```js
// use HTTPS(true) in case you are behind a load balancer (e.g. Heroku)
```

This is now deprecated. The comment should either refer to the new `enforce.HTTPS({ trustProtoHeader: true })` option or else just be removed entirely, since the later section in the readme deals with it.

**Comment by florianheinemann** [comment]
Thank you! Fixed & closed

**Comment by edmorley** [comment]
Many thanks :-)
