### ISSUE TITLE
listen to both ports at the same time

### ISSUE THREAD

**Issue by mderazon** [florianheinemann/express-sslify#13]
as far as the example goes, i'm not sure how do you listen to both ports at the same time?

``` js
var express = require('express');
var http = require('http');
var enforce = require('express-sslify');

var app = express();
app.use(enforce.HTTPS());

http.createServer(app).listen(app.get('port'), function() {
    console.log('Express server listening on port ' + app.get('port'));
});
```

why do you wrap express app with another server ?

**Comment by florianheinemann** [comment]
Hi!

You're wondering about `createServer()`? That's simply the verbose way of what is usually hidden behind `app.listen()`. More about this and also about how to listen to HTTP and HTTPS in the express documentation: http://expressjs.com/api.html#app.listen

As you'll see the verbose way is also a great way of configuring your routes, etc. in one central `app` object and then passing it to a HTTP and a HTTPS server without redoing all your routes, etc.

Hope that helps!
