### ISSUE TITLE
Next() for Localhost

### ISSUE THREAD

**Issue by grod220** [florianheinemann/express-sslify#22]
Whenever I use this package, it doesn't work in my local environment because https://localhost:### throws errors. Can we add another check like this?

if(req.headers && req.headers.host && req.headers.host === 'localhost:####') {
    next();
}

**Comment by ghost** [comment]
Maybe just do something like this?

```
if (app.get("env") === "production") {
   app.use(enforce.HTTPS({ trustProtoHeader: true }));
}
```
