### ISSUE TITLE
misleading/meaningless arguments

### ISSUE THREAD

**Issue by venil7** [florianheinemann/express-sslify#5]
I think arguments are absolutely menaingless

`app.use(enforce.HTTPS(false, true))`

instead that should be something like

`app.use(enforce.HTTPS({azure: true, heroku: true}))`

**Comment by florianheinemann** [comment]
Hi!

You're right - The alternative might be nicer. If you bring in a PR incl. the tests I would certainly merge. We should probably allow both options for the foreseeable future. 

Florian

**Comment by turboMaCk** [comment]
@florianheinemann Let me know if you're OK with that PR.

**Comment by florianheinemann** [comment]
Hey - Looks great, thanks! I'll merge and publish it over the weekend. Bit busy right now :)

**Comment by venil7** [comment]
:+1:
